exports.seed = knex => {
  // Deletes ALL existing entries
  return knex('problems').del()
    .then(() => {
      // Inserts seed entries
      return knex('problems').insert([
        {id: 1, age:32, gender_id:4, race_id:4, lat:'1.000143', long:'43.99999465', type_id:2, other:null, viewpoint:'stop', noun:'Neighborhood BBQs', action:"poorly planned", reason:"there isn't a good place to list what you are bringing", story:"It would be great if there was a group-centric food app that enhanced and brought excitement to BBQ, pot luck or any food-involved gatherings."},
        {id: 2, age:29, gender_id:1, race_id:6, lat:'1.000143', long:'43.99999465', type_id:2, other:null, viewpoint:'stop', noun:'all food trucks', action:"so hard to find", reason:"there isn't a good place to find all food trucks in my area", story:"It would be great if there was a food truck app finder that located food trucks in and round my neighborhood, where I could view menus, receive their daily deals and essentially enjoy my meal on the move!"},
        {id: 3, age:21, gender_id:5, race_id:4, lat:'1.000143', long:'43.99999465', type_id:4, other:null, viewpoint:'happen', noun:'Tenant/Landlords', action:"would have a place to communiticate like an app", reason:"the communication systems are outdated", story:'My landlord needs to simplify their communication with tenants'},
        {id: 4, age:23, gender_id:1, race_id:3, lat:'1.000143', long:'43.99999465', type_id:5, other:null, viewpoint:'happen', noun:'Students', action:"have a place to take notes while watching videos", reason:"they could have timestamps on the youtube videos they need to watch", story:"I really want to be able to take notes while watching an educational video."},
        {id: 5, age:32, gender_id:4, race_id:3, lat:'1.000143', long:'43.99999465', type_id:1, other:null, viewpoint:'happen', noun:'all restaurants and offices', action:'be required to use compostable or recyclable packaging', reason:'we would put less plastic and styrofoam into the landfills', story:'we would put less plastic and styrofoam into the landfills'},
        {id: 6, age:18, gender_id:2, race_id:5, lat:'1.000143', long:'43.99999465', type_id:3, other:null, viewpoint:'stop', noun:'public spaces', action:'forcing people to use binary gender bathrooms', reason:'it alienates people and puts them in danger', story:'I get stared at and sometimes harassed when I go into bathrooms. Cis people dont understand what its like to feel out of place in bathroom.'},
        {id: 7, age:56, gender_id:5, race_id:3, lat:'1.000143', long:'43.99999465', type_id:4, other:null, viewpoint:'stop', noun:'the tech industry', action:'not working harder to achieve diversity', reason:'our projects could be so much more impactful', story:null},
        {id: 8, age:22, gender_id:4, race_id:1, lat:'1.000143', long:'43.99999465', type_id:4, other:null, viewpoint:'happen', noun:'hospitals', action:'serve better food', reason:'people who are trying to heal didnt have to each such crappy food.', story:'when my little brother recovering from pneumonia, the hospital food was so terrible. It hardly seems productive to feed sick people processed, overcooked food.'},
        {id: 9, age:32, gender_id:5, race_id:2, lat:'1.000143', long:'43.99999465', type_id:2, other:null, viewpoint:'happen', noun:'the cannabis industry', action:'continue funding education forever', reason:'we could undo some of the damage TABOR did and be a competitive state', story:null},
        {id: 10, age:47, gender_id:3, race_id:4, lat:'1.000143', long:'43.99999465', type_id:3, other:null, viewpoint:'stop', noun:'all restaurants and offices', action:'be required to use compostable or recyclable packaging', reason:'we would put less plastic and styrofoam into the landfills', story:'we would put less plastic and styrofoam into the landfills'},
        {id: 11, age:30, gender_id:2, race_id:2, lat:'1.000143', long:'43.99999465', type_id:3, other:null, viewpoint:'happen', noun:'all restaurants and offices', action:'be required to use compostable or recyclable packaging', reason:'we would put less plastic and styrofoam into the landfills', story:'we would put less plastic and styrofoam into the landfills'},
        {id: 12, age:24, gender_id:1, race_id:2, lat:'1.000143', long:'43.99999465', type_id:4, other:null, viewpoint:'happen', noun:'companies', action:"offer parental leave for both parents", reason:"so that both parents have the opportunity to be present in their baby's beginning", story:''},
        {id: 13, age:47, gender_id:5, race_id:6, lat:'1.000143', long:'43.99999465', type_id:4, other:null, viewpoint:'happen', noun:'companies', action:"offer paternity leave", reason:"so dads can be present in their baby's beginning", story:null },
        {id: 14, age:34, gender_id:4, race_id:5, lat:'1.000143', long:'43.99999465', type_id:1, other:null, viewpoint:'happen', noun:'government', action:"pass stronger policies that protect our National Forests", reason:"so we are protecting Mother Earth and preversing our land", story:''},
        {id: 15, age:42, gender_id:5, race_id:6, lat:'1.000143', long:'43.99999465', type_id:5, other:null, viewpoint:'stop', noun:'CVS/Pharmacies', action:"accept good RX across the board", reason:"because their policy varies manager to manager", story:"I'd like to know ahead of time of what CVS accepts rather then it depending on the manager"},
        {id: 16, age:23, gender_id:4, race_id:2, lat:'1.000143', long:'43.99999465', type_id:2, other:null, viewpoint:'happen', noun:'Neighborhood Watch', action:"community to take action to safeguard it self", reason:"so communities aren't completely reliant of police officers", story:"If communities were more proactive in protecting themselves, there would be less dependence on police force which would give officers time for other matters and give communities independence."},
        {id: 17, age:33, gender_id:6, race_id:1, lat:'1.000143', long:'43.99999465', type_id:3, other:null, viewpoint:'stop', noun:'Galvanize', action:"would provide two instructors per cohort", reason:"because I was promised this, I think?", story:""},
        {id: 18, age:32, gender_id:4, race_id:4, lat:'1.000143', long:'43.99999465', type_id:2, other:null, viewpoint:'stop', noun:'Neighborhood BBQs', action:"poorly planned", reason:"there isn't a good place to list what you are bringing", story:"It would be great if there was a group-centric food app that enhanced and brought excitement to BBQ, pot luck or any food-involved gatherings."},
        {id: 19, age:29, gender_id:1, race_id:6, lat:'1.000143', long:'43.99999465', type_id:2, other:null, viewpoint:'stop', noun:'all food trucks', action:"so hard to find", reason:"there isn't a good place to find all food trucks in my area", story:"It would be great if there was a food truck app finder that located food trucks in and round my neighborhood, where I could view menus, receive their daily deals and essentially enjoy my meal on the move!"},
        {id: 20, age:21, gender_id:5, race_id:4, lat:'1.000143', long:'43.99999465', type_id:4, other:null, viewpoint:'happen', noun:'Tenant/Landlords', action:"would have a place to communiticate like an app", reason:"the communication systems are outdated", story:'My landlord needs to simplify their communication with tenants'},
        {id: 21, age:23, gender_id:1, race_id:3, lat:'1.000143', long:'43.99999465', type_id:5, other:null, viewpoint:'happen', noun:'Students', action:"have a place to take notes while watching videos", reason:"they could have timestamps on the youtube videos they need to watch", story:"I really want to be able to take notes while watching an educational video."},
        {id: 22, age:32, gender_id:4, race_id:3, lat:'1.000143', long:'43.99999465', type_id:1, other:null, viewpoint:'happen', noun:'all restaurants and offices', action:'be required to use compostable or recyclable packaging', reason:'we would put less plastic and styrofoam into the landfills', story:'we would put less plastic and styrofoam into the landfills'},
        {id: 23, age:18, gender_id:2, race_id:5, lat:'1.000143', long:'43.99999465', type_id:3, other:null, viewpoint:'stop', noun:'public spaces', action:'forcing people to use binary gender bathrooms', reason:'it alienates people and puts them in danger', story:'I get stared at and sometimes harassed when I go into bathrooms. Cis people dont understand what its like to feel out of place in bathroom.'},
        {id: 24, age:56, gender_id:5, race_id:3, lat:'1.000143', long:'43.99999465', type_id:4, other:null, viewpoint:'stop', noun:'the tech industry', action:'not working harder to achieve diversity', reason:'our projects could be so much more impactful', story:null},
        {id: 25, age:22, gender_id:4, race_id:1, lat:'1.000143', long:'43.99999465', type_id:4, other:null, viewpoint:'happen', noun:'hospitals', action:'serve better food', reason:'people who are trying to heal didnt have to each such crappy food.', story:'when my little brother recovering from pneumonia, the hospital food was so terrible. It hardly seems productive to feed sick people processed, overcooked food.'},
        {id: 26, age:32, gender_id:5, race_id:2, lat:'1.000143', long:'43.99999465', type_id:2, other:null, viewpoint:'happen', noun:'the cannabis industry', action:'continue funding education forever', reason:'we could undo some of the damage TABOR did and be a competitive state', story:null},
        {id: 27, age:47, gender_id:3, race_id:4, lat:'1.000143', long:'43.99999465', type_id:3, other:null, viewpoint:'stop', noun:'all restaurants and offices', action:'be required to use compostable or recyclable packaging', reason:'we would put less plastic and styrofoam into the landfills', story:'we would put less plastic and styrofoam into the landfills'},
        {id: 28, age:30, gender_id:2, race_id:2, lat:'1.000143', long:'43.99999465', type_id:3, other:null, viewpoint:'happen', noun:'all restaurants and offices', action:'be required to use compostable or recyclable packaging', reason:'we would put less plastic and styrofoam into the landfills', story:'we would put less plastic and styrofoam into the landfills'},
        {id: 29, age:24, gender_id:1, race_id:2, lat:'1.000143', long:'43.99999465', type_id:4, other:null, viewpoint:'happen', noun:'companies', action:"offer parental leave for both parents", reason:"so that both parents have the opportunity to be present in their baby's beginning", story:''},
        {id: 30, age:47, gender_id:5, race_id:6, lat:'1.000143', long:'43.99999465', type_id:4, other:null, viewpoint:'happen', noun:'companies', action:"offer paternity leave", reason:"so dads can be present in their baby's beginning", story:null },
        {id: 31, age:34, gender_id:4, race_id:5, lat:'1.000143', long:'43.99999465', type_id:1, other:null, viewpoint:'happen', noun:'government', action:"pass stronger policies that protect our National Forests", reason:"so we are protecting Mother Earth and preversing our land", story:''},
        {id: 32, age:42, gender_id:5, race_id:6, lat:'1.000143', long:'43.99999465', type_id:5, other:null, viewpoint:'stop', noun:'CVS/Pharmacies', action:"accept good RX across the board", reason:"because their policy varies manager to manager", story:"I'd like to know ahead of time of what CVS accepts rather then it depending on the manager"},
        {id: 33, age:23, gender_id:4, race_id:2, lat:'1.000143', long:'43.99999465', type_id:2, other:null, viewpoint:'happen', noun:'Neighborhood Watch', action:"community to take action to safeguard it self", reason:"so communities aren't completely reliant of police officers", story:"If communities were more proactive in protecting themselves, there would be less dependence on police force which would give officers time for other matters and give communities independence."},
        {id: 34, age:33, gender_id:6, race_id:1, lat:'1.000143', long:'43.99999465', type_id:3, other:null, viewpoint:'stop', noun:'Galvanize', action:"would provide two instructors per cohort", reason:"because I was promised this, I think?", story:""}
      ]);
    }).then(() => {
      return knex.raw(`SELECT setval('problems_id_seq', (SELECT MAX(id) FROM problems));`)
      })
}
